import { useState } from 'react'
import { useNavigate, useLocation } from 'react-router-dom'
import { ShieldCheck, Loader2, LogOut, CheckCircle2 } from 'lucide-react'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { useAuthStore } from '@/features/auth/store/useAuthStore'
import { useVerify2FA } from '@/features/auth/2fa/hooks/use2FA'
import { logoutUser } from '@/features/auth/api/authApi'
import { setDevice2FAVerified, clearDevice2FAVerified } from '@/features/auth/2fa/lib/twoFactorStorage'

export default function TwoFactorPage() {
  const navigate = useNavigate()
  const location = useLocation()
  const isTwoFactorRequired = useAuthStore((s) => s.isTwoFactorRequired)
  const setTwoFactorVerified = useAuthStore((s) => s.setTwoFactorVerified)
  const setTwoFactorRequired = useAuthStore((s) => s.setTwoFactorRequired)
  const user = useAuthStore((s) => s.user)
  const firebaseUser = useAuthStore((s) => s.firebaseUser)
  const verifyMutation = useVerify2FA()

  const [code, setCode] = useState('')
  const [useBackupCode, setUseBackupCode] = useState(false)
  const [rememberDevice, setRememberDevice] = useState(true)

  const fromLocation = (location.state as { from?: { pathname: string } } | null)?.from
  const destination = fromLocation?.pathname && fromLocation.pathname !== '/2fa'
    ? fromLocation.pathname
    : '/'

  const handleVerify = (e: React.FormEvent) => {
    e.preventDefault()
    const clean = code.trim()
    if (!clean) {
      toast.error('Please enter a verification code.')
      return
    }

    verifyMutation.mutate(
      useBackupCode ? { backupCode: clean } : { code: clean.replace(/\D/g, '') },
      {
        onSuccess: (verified) => {
          if (verified) {
            const uid = user?.firebaseUid || firebaseUser?.uid
            if (rememberDevice && uid) {
              setDevice2FAVerified(uid)
            }
            setTwoFactorVerified(true)
            setTwoFactorRequired(false)
            toast.success('Two-factor authentication verified successfully.')
            navigate(destination, { replace: true })
          } else {
            toast.error('Invalid authentication code. Please try again.')
          }
        },
        onError: (err) => {
          console.error('[OpenMosque] 2FA verification failed:', err)
          toast.error('Verification failed. Invalid code or consumed backup code.')
        },
      },
    )
  }

  const handleSignOut = async () => {
    const uid = user?.firebaseUid || firebaseUser?.uid
    clearDevice2FAVerified(uid)
    await logoutUser()
    navigate('/login', { replace: true })
    toast.success('Signed out.')
  }

  // If the user lands here directly and 2FA is already satisfied
  if (!isTwoFactorRequired) {
    return (
      <div className="flex min-h-[70vh] items-center justify-center px-4 py-12">
        <Card className="w-full max-w-md text-center border-border">
          <CardHeader>
            <div className="mx-auto flex size-12 items-center justify-center rounded-full bg-primary/10 text-primary mb-2">
              <CheckCircle2 className="size-6" />
            </div>
            <CardTitle className="text-xl">2FA Is Already Verified</CardTitle>
            <CardDescription>
              Your session has already completed two-factor verification.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            <Button className="w-full" onClick={() => navigate('/security-settings')}>
              Manage Security Settings
            </Button>
            <Button variant="ghost" className="w-full" onClick={() => navigate('/')}>
              Return to Home
            </Button>
          </CardContent>
        </Card>
      </div>
    )
  }

  return (
    <div className="flex min-h-[75vh] items-center justify-center px-4 py-12">
      <Card className="w-full max-w-md border-border shadow-sm">
        <CardHeader className="text-center">
          <div className="mx-auto flex size-12 items-center justify-center rounded-full bg-primary/10 text-primary mb-2">
            <ShieldCheck className="size-6" />
          </div>
          <CardTitle className="text-2xl">Two-Factor Challenge</CardTitle>
          <CardDescription>
            {useBackupCode
              ? 'Enter one of your 8-character one-time backup recovery codes.'
              : 'Enter the 6-digit security code generated by your authenticator app.'}
          </CardDescription>
        </CardHeader>

        <CardContent className="space-y-6">
          <form onSubmit={handleVerify} className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="challenge-code">
                {useBackupCode ? 'Backup Recovery Code' : '6-Digit Verification Code'}
              </Label>
              <Input
                id="challenge-code"
                type="text"
                autoComplete="one-time-code"
                placeholder={useBackupCode ? 'XXXX-XXXX' : '123456'}
                value={code}
                onChange={(e) => setCode(e.target.value)}
                maxLength={useBackupCode ? 12 : 6}
                className="font-mono text-center text-xl tracking-widest h-12"
                autoFocus
              />
            </div>

            <div className="flex items-center gap-2 pt-1">
              <input
                id="remember-device"
                type="checkbox"
                checked={rememberDevice}
                onChange={(e) => setRememberDevice(e.target.checked)}
                className="size-4 rounded border-border text-primary focus:ring-primary accent-primary"
              />
              <Label htmlFor="remember-device" className="text-xs text-muted-foreground cursor-pointer select-none">
                Don't ask for codes again on this browser
              </Label>
            </div>

            <Button
              type="submit"
              className="w-full h-10 font-semibold"
              disabled={verifyMutation.isPending || !code.trim()}
            >
              {verifyMutation.isPending ? <Loader2 className="size-4 animate-spin" /> : null}
              Verify & Continue
            </Button>
          </form>

          <div className="flex flex-col items-center gap-3 pt-2 text-center text-sm border-t border-border">
            <button
              type="button"
              onClick={() => {
                setUseBackupCode(!useBackupCode)
                setCode('')
              }}
              className="text-xs text-primary font-medium hover:underline"
            >
              {useBackupCode ? 'Use 6-digit authenticator app code' : 'Lost your phone? Use a backup code'}
            </button>

            <button
              type="button"
              onClick={handleSignOut}
              className="inline-flex items-center gap-1 text-xs text-muted-foreground hover:text-foreground mt-1"
            >
              <LogOut className="size-3" />
              Sign out of this account
            </button>
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
