import { useState } from 'react'
import {
  ShieldCheck,
  ShieldAlert,
  KeyRound,
  RefreshCw,
  ShieldOff,
  CheckCircle2,
  Lock,
  Smartphone,
  Loader2,
} from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { use2FAStatus } from '@/features/auth/2fa/hooks/use2FA'
import { Setup2FAModal } from '@/features/auth/2fa/components/Setup2FAModal'
import { Disable2FAModal } from '@/features/auth/2fa/components/Disable2FAModal'
import { RegenerateBackupCodesModal } from '@/features/auth/2fa/components/RegenerateBackupCodesModal'
import { useAuthStore } from '@/features/auth/store/useAuthStore'

export default function SecuritySettingsPage() {
  const user = useAuthStore((s) => s.user)
  const { data: statusData, isLoading } = use2FAStatus()

  const [setupModalOpen, setSetupModalOpen] = useState(false)
  const [disableModalOpen, setDisableModalOpen] = useState(false)
  const [regenModalOpen, setRegenModalOpen] = useState(false)

  const is2FAEnabled = statusData?.enabled ?? false
  const remainingCodes = statusData?.remainingBackupCodes ?? 0

  return (
    <div className="container mx-auto max-w-4xl space-y-6 py-6 px-4">
      <div>
        <div className="flex items-center gap-3">
          <div className="flex size-10 items-center justify-center rounded-lg bg-primary/10 text-primary">
            <ShieldCheck className="size-6" />
          </div>
          <div>
            <h1 className="text-2xl font-bold tracking-tight text-foreground sm:text-3xl">
              Security Settings
            </h1>
            <p className="text-sm text-muted-foreground mt-0.5">
              Manage two-factor authentication and account security protections.
            </p>
          </div>
        </div>
      </div>

      <div className="grid gap-6">
        {/* Two-Factor Authentication Card */}
        <Card className="border-border">
          <CardHeader>
            <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
              <div>
                <CardTitle className="flex items-center gap-2 text-xl">
                  <Smartphone className="size-5 text-primary" />
                  Two-Factor Authentication (TOTP)
                </CardTitle>
                <CardDescription className="mt-1">
                  Add an extra layer of security requiring a one-time code from your authenticator app.
                </CardDescription>
              </div>

              {isLoading ? (
                <div className="flex items-center gap-2 text-sm text-muted-foreground">
                  <Loader2 className="size-4 animate-spin text-primary" />
                  <span>Loading status…</span>
                </div>
              ) : is2FAEnabled ? (
                <div className="flex items-center gap-2 self-start rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold text-primary">
                  <CheckCircle2 className="size-3.5" />
                  <span>Active & Protected</span>
                </div>
              ) : (
                <div className="flex items-center gap-2 self-start rounded-full bg-muted px-3 py-1 text-xs font-medium text-muted-foreground">
                  <ShieldAlert className="size-3.5" />
                  <span>Disabled</span>
                </div>
              )}
            </div>
          </CardHeader>

          <CardContent className="space-y-6">
            {isLoading ? (
              <div className="flex h-36 items-center justify-center">
                <Loader2 className="size-6 animate-spin text-primary" />
              </div>
            ) : is2FAEnabled ? (
              <div className="space-y-6">
                <div className="rounded-lg border border-border/80 bg-muted/30 p-4 space-y-3">
                  <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2">
                    <div>
                      <p className="text-sm font-semibold text-foreground">Authenticator App Configured</p>
                      <p className="text-xs text-muted-foreground">
                        Codes generated by Google Authenticator, Authy, or Microsoft Authenticator will be requested upon login.
                      </p>
                    </div>
                    <div className="text-xs font-medium text-muted-foreground">
                      <span className="font-bold text-foreground">{remainingCodes}</span> backup recovery codes remaining
                    </div>
                  </div>
                </div>

                <div className="flex flex-wrap items-center gap-3 pt-2">
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={() => setRegenModalOpen(true)}
                    className="gap-1.5"
                  >
                    <RefreshCw className="size-4 text-muted-foreground" />
                    Regenerate Backup Codes
                  </Button>

                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={() => setDisableModalOpen(true)}
                    className="gap-1.5 text-destructive hover:text-destructive hover:bg-destructive/10"
                  >
                    <ShieldOff className="size-4" />
                    Disable 2FA
                  </Button>
                </div>
              </div>
            ) : (
              <div className="space-y-4">
                <p className="text-sm text-muted-foreground leading-relaxed">
                  Protect your OpenMosque account from unauthorized access. When two-factor authentication is active,
                  you will be prompted to enter a 6-digit verification code from your authenticator app whenever you sign in.
                </p>

                <div className="pt-2">
                  <Button
                    type="button"
                    onClick={() => setSetupModalOpen(true)}
                    className="gap-2"
                  >
                    <KeyRound className="size-4" />
                    Set Up Two-Factor Authentication
                  </Button>
                </div>
              </div>
            )}
          </CardContent>
        </Card>

        {/* Account Info & Security Overview */}
        <Card className="border-border">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-xl">
              <Lock className="size-5 text-primary" />
              Account Security Overview
            </CardTitle>
            <CardDescription>
              Details about your authenticated identity and platform role.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
              <div className="rounded-lg border border-border p-3.5 bg-card">
                <span className="text-xs font-medium text-muted-foreground">Signed-in Email</span>
                <p className="mt-1 text-sm font-semibold text-foreground truncate">
                  {user?.email || 'Unknown'}
                </p>
              </div>

              <div className="rounded-lg border border-border p-3.5 bg-card">
                <span className="text-xs font-medium text-muted-foreground">Assigned Role</span>
                <p className="mt-1 text-sm font-semibold text-primary">
                  {user?.role || 'USER'}
                </p>
              </div>

              <div className="rounded-lg border border-border p-3.5 bg-card">
                <span className="text-xs font-medium text-muted-foreground">Contribution Points</span>
                <p className="mt-1 text-sm font-semibold text-foreground">
                  {user?.points ?? 0} points
                </p>
              </div>

              <div className="rounded-lg border border-border p-3.5 bg-card">
                <span className="text-xs font-medium text-muted-foreground">Authentication Method</span>
                <p className="mt-1 text-sm font-semibold text-foreground">
                  Firebase Identity Provider (Stateless JWT)
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Modals */}
      <Setup2FAModal open={setupModalOpen} onOpenChange={setSetupModalOpen} />
      <Disable2FAModal open={disableModalOpen} onOpenChange={setDisableModalOpen} />
      <RegenerateBackupCodesModal open={regenModalOpen} onOpenChange={setRegenModalOpen} />
    </div>
  )
}
